### ISSUE TITLE
点击登录按钮报了一个错误

### ISSUE THREAD

**Issue by findjh** [qufei1993/nextjs-learn-cn#2]
## 问题：点击登录按钮报了一个错误：
Failed to fetch user: Error: Query values must be an array
    at D:\Project\nextjs-dashboard-final\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.sql (webpack-internal:///(action-browser)/./app/lib/pg-local.ts:17:17)

## 解决：query方法的参数应该是要求数组？
![image](https://github.com/qufei1993/nextjs-learn-cn/assets/51046272/6883fe00-23a5-4a2d-8f46-93e12ce5cef2)

**Comment by qufei1993** [comment]
上面图片是 [migration 脚本](https://github.com/qufei1993/nextjs-learn-example/blob/main/scripts/pg-local.js)里的，是没问题的，因为上面 `values` 没有展开传递。

业务代码用到的是 TS 版本，在这里 [https://github.com/qufei1993/nextjs-learn-example/blob/main/app/lib/pg-local.ts](https://github.com/qufei1993/nextjs-learn-example/blob/main/app/lib/pg-local.ts) 你参考这个最新代码就好了，可以看看这个文档的描述 https://qufei1993.github.io/nextjs-learn-cn/chapter17

**Comment by findjh** [comment]
> 上面图片是 [migration 脚本](https://github.com/qufei1993/nextjs-learn-example/blob/main/scripts/pg-local.js)里的，是没问题的，因为上面 `values` 没有展开传递。
> 
> 业务代码用到的是 TS 版本，在这里 https://github.com/qufei1993/nextjs-learn-example/blob/main/app/lib/pg-local.ts 你参考这个最新代码就好了，可以看看这个文档的描述 https://qufei1993.github.io/nextjs-learn-cn/chapter17

thanks
