### ISSUE TITLE
问答模块除了第一个以外 其他的问答无法点击 会跳回到第一个问题

### ISSUE THREAD

**Issue by foreinbug** [qufei1993/nextjs-learn-cn#4]
Microsoft Edge
123.0.2420.81 
Firefox
124.0.1

**Comment by Nightclose-L** [comment]
也不是不能点，是只能点 radio 的部分，因为 label-for 指向的 id 有重复，所以都跳回第一个匹配的了（原理是我的推测，但 for 指向自测过修改为不重复的就可以）

**Comment by qufei1993** [comment]
已修复，原因如上面 @Nightclose-L 指出的，label htmlFor 指向的 input id 有重复，用 md5 做了 hash code，可以解决该问题，参见 [Link](https://github.com/qufei1993/nextjs-learn-cn/commit/e391a7a70ede4e3cdad7247212a6fea61671c8ff#diff-0f264510776f58e06d5e8350995c9c6e10e4e53c63bc7ffced99e3a992ad5c93)
