### ISSUE TITLE
首页的下一章跳转按钮的 href 是 Chapter 2 的链接

### ISSUE THREAD

**Issue by Sheldonsix** [qufei1993/nextjs-learn-cn#5]
个人感觉应该是 `Chapter 1: 入门` 的链接。

![image](https://github.com/qufei1993/nextjs-learn-cn/assets/42886406/57dca729-6ed3-4811-8702-d163715bff84)

**Comment by qufei1993** [comment]
已修复，原因是之前有个介绍页隐藏了，现在展示出来了，参见 [Link]( https://github.com/qufei1993/nextjs-learn-cn/commit/e391a7a70ede4e3cdad7247212a6fea61671c8ff#diff-17be8492ca585928ea40960b5a6f48a8f48a4ae636d39966d8af749f63e0403f)
