### ISSUE TITLE
Chapter 6 建立你的数据库之浏览你的数据库

### ISSUE THREAD

**Issue by Phizumi** [qufei1993/nextjs-learn-cn#6]
**填充你的数据库** 之后，我认为最好加上，push 代码，让 vercel 自动部署的说明，然后再是 **浏览你的数据库**。
我在本地执行完 seed 命令后，也没有报错，然后直接去 vercel，结果看不到 table，经过一系列搜索，猜测是不是要推代码，重新部署。

**Comment by qufei1993** [comment]
seed 命令就是用来执行脚本填充数据的，确认下数据库地址、环境是否有误。

**Comment by kiwiflydream** [comment]
同样卡在第 6 章，发现原版已经更新了文档，不是执行脚本，而是通过访问路由，最好同步修改一下

![CleanShot 28062024--at 22 33 27@2x](https://github.com/qufei1993/nextjs-learn-cn/assets/13311001/4938c384-6b9b-4117-a2d3-d5b97c0480c9)
